/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RoleManagementLazyImport = createFileRoute('/role-management')()
const PermissionManagementLazyImport = createFileRoute(
  '/permission-management',
)()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RoleManagementLazyRoute = RoleManagementLazyImport.update({
  id: '/role-management',
  path: '/role-management',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/role-management.lazy').then((d) => d.Route),
)

const PermissionManagementLazyRoute = PermissionManagementLazyImport.update({
  id: '/permission-management',
  path: '/permission-management',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/permission-management.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/permission-management': {
      id: '/permission-management'
      path: '/permission-management'
      fullPath: '/permission-management'
      preLoaderRoute: typeof PermissionManagementLazyImport
      parentRoute: typeof rootRoute
    }
    '/role-management': {
      id: '/role-management'
      path: '/role-management'
      fullPath: '/role-management'
      preLoaderRoute: typeof RoleManagementLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/permission-management': typeof PermissionManagementLazyRoute
  '/role-management': typeof RoleManagementLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/permission-management': typeof PermissionManagementLazyRoute
  '/role-management': typeof RoleManagementLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/permission-management': typeof PermissionManagementLazyRoute
  '/role-management': typeof RoleManagementLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/permission-management' | '/role-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/permission-management' | '/role-management'
  id: '__root__' | '/' | '/permission-management' | '/role-management'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PermissionManagementLazyRoute: typeof PermissionManagementLazyRoute
  RoleManagementLazyRoute: typeof RoleManagementLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PermissionManagementLazyRoute: PermissionManagementLazyRoute,
  RoleManagementLazyRoute: RoleManagementLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/permission-management",
        "/role-management"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/permission-management": {
      "filePath": "permission-management.lazy.tsx"
    },
    "/role-management": {
      "filePath": "role-management.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
